/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zjicm_aicamera_Factory */

#ifndef _Included_org_zjicm_aicamera_Factory
#define _Included_org_zjicm_aicamera_Factory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zjicm_aicamera_Factory
 * Method:    changeImage
 * Signature: (JJ)J
 */
JNIEXPORT void JNICALL Java_org_zjicm_aicamera_Factory_changeImage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
